# Generated by Django 3.2.18 on 2023-05-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_buylog_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCode',
            fields=[
                ('userName', models.CharField(max_length=16, serialize=False)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
