# Generated by Django 3.2.18 on 2023-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_tempcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcode',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='tempcode',
            name='userName',
            field=models.CharField(max_length=16),
        ),
    ]
