# Generated by Django 3.2.18 on 2023-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230510_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcode',
            name='authority',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempcode',
            name='email1',
            field=models.EmailField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
