# Generated by Django 3.2.18 on 2023-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230511_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
