# Generated by Django 3.2.18 on 2023-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230513_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylog',
            name='goodsName',
            field=models.CharField(max_length=32),
        ),
    ]
