# Generated by Django 3.2.18 on 2023-05-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_buylog_goodsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopCart', models.CharField(max_length=65530)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.members')),
            ],
        ),
    ]
