# Generated by Django 3.2.18 on 2023-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buylog',
            name='goodsName',
        ),
        migrations.RemoveField(
            model_name='buylog',
            name='price',
        ),
        migrations.RemoveField(
            model_name='buylog',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='buylog',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='buylog',
            name='logjson',
            field=models.CharField(default=1, max_length=65530),
            preserve_default=False,
        ),
    ]
