# Generated by Django 3.2.18 on 2023-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20230620_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylog',
            name='kind',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
