# Generated by Django 3.2.18 on 2023-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_buylog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='ip',
            field=models.GenericIPAddressField(default="127.0.0.1"),
            preserve_default=False,
        ),
    ]
