# Generated by Django 3.2.19 on 2023-07-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_operationlog_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrowsinglog',
            name='userName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.members'),
        ),
    ]
